# Query to retrieve protein data
# Defensive query: assumes that data does not conform to Protein profile
# Retrieve all properties that are mentioned in the Protein Profile
# Proteins are grouped by their IRI, with multiple values possible

PREFIX schema: <https://schema.org/>
PREFIX pav: <http://purl.org/pav/>
SELECT  ?s
	(GROUP_CONCAT(DISTINCT ?description;SEPARATOR=',<br/>') AS ?descriptions)
	(GROUP_CONCAT(DISTINCT ?keywords;SEPARATOR=',<br/>') AS ?keywordss)
	(GROUP_CONCAT(DISTINCT ?name;SEPARATOR=',<br/>') AS ?names)
	(GROUP_CONCAT(DISTINCT ?provider;SEPARATOR=',<br/>') AS ?providers)
	(GROUP_CONCAT(DISTINCT ?url;SEPARATOR=',<br/>') AS ?urls)
	(GROUP_CONCAT(DISTINCT ?about;SEPARATOR=',<br/>') AS ?topics)
	(GROUP_CONCAT(DISTINCT ?alternateName;SEPARATOR=',<br/>') AS ?altNames)
	(GROUP_CONCAT(DISTINCT ?citation;SEPARATOR=',<br/>') AS ?citations)
	(GROUP_CONCAT(DISTINCT ?dataset;SEPARATOR=',<br/>') AS ?datasets)
	(GROUP_CONCAT(DISTINCT ?dateCreated;SEPARATOR=',<br/>') AS ?dateCreateds)
	(GROUP_CONCAT(DISTINCT ?identifier;SEPARATOR=',<br/>') AS ?identifiers)
	(GROUP_CONCAT(DISTINCT ?license;SEPARATOR=',<br/>') AS ?licenses)
	(GROUP_CONCAT(DISTINCT ?sourceOrganization;SEPARATOR=',<br/>') AS ?sourceOrganizations)
	(GROUP_CONCAT(DISTINCT ?dateModified;SEPARATOR=',<br/>') AS ?modifiedDates)
	(GROUP_CONCAT(DISTINCT ?encodingFormat;SEPARATOR=',<br/>') AS ?formats)
	(GROUP_CONCAT(DISTINCT ?sameAs;SEPARATOR=',<br/>') AS ?equivalences)
	(GROUP_CONCAT(DISTINCT ?source;SEPARATOR=',<br/>') AS ?sources)
WHERE {
	GRAPH ?g {
## Bioschemas Minimal Properties
		?s a schema:DataCatalog .
		OPTIONAL {?s schema:description ?description}
		OPTIONAL {?s schema:keywords ?keywords}
		OPTIONAL {?s schema:name ?name }
		OPTIONAL {?s schema:provider ?provider}
		OPTIONAL {?s schema:url ?url}
## Bioschemas Recommended properties
		OPTIONAL {?s schema:about ?about}
		OPTIONAL {?s schema:alternateName ?altName}
		OPTIONAL {?s schema:citation ?citation}
		OPTIONAL {?s schema:dataset ?dataset }
		OPTIONAL {?s schema:dateCreated ?dateCreated}
		OPTIONAL {?s schema:identifier ?identifier }
		OPTIONAL {?s schema:license ?license }
		OPTIONAL {?s schema:sourceOrganization ?sourceOrganization}
## Bioschemas Optional properties
		OPTIONAL {?s schema:dateModified ?dateModified}
		OPTIONAL {?s schema:encodingFormat ?encodingFormat}
		OPTIONAL {?s schema:sameAs ?sameAs }
	}
	?g pav:retrievedFrom ?source
}
GROUP BY ?s
