# Number of annotations by term code
# For each term code, return the number of annotations using that code.

PREFIX schema: <https://schema.org/>
PREFIX void: <http://rdfs.org/ns/void#>

SELECT ?termCode (SAMPLE(?termName) AS ?name) (COUNT (?annotation) AS ?numAnnotations)
WHERE {
    graph ?g {
        ?annotation schema:additionalProperty/schema:value ?term .
        ?term schema:termCode ?termCode ;
            schema:name ?termName .
    }
}
GROUP BY ?termCode
ORDER BY DESC(?numAnnotations)
